language: c++

## Platforms
matrix:
    include:
        - os: linux
        - os: windows
        - os: osx

## Build
script:
    - cmake --build .
    - cmake --build . --target tests
    - ctest .
