language: c++

## Packages
addons:
    homebrew:
        packages:
            - llvm
    apt:
        packages:
            - llvm
    chocolatey:
        packages:
            - llvm

## Platforms
os:
  - linux
  - windows
  - osx

## Compilers
compiler:
  - clang
  - gcc

## Build
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build .
  - cmake --build . --target tests
  - ctest .
