language: c++

## Platforms
os:
  - linux
  - windows
  - osx

## Compilers
compiler:
  - clang
  - gcc

## Build
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build .
  - cmake --build . --target tests
  - ctest .
