## It seems that windows does not support `c++`, even though `cpp` works fine
language: cpp

## Platforms
os:
  - linux
  - windows
  - osx
## For some reason, default osx image is not working with homebrew
osx_image: xcode10.2

## Compilers
compiler:
  - clang
  - gcc

## Install step
apt:
  sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-6.0
install:
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        choco install -y llvm;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt update;
        sudo apt install llvm-dev clang-dev -y;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew install llvm;
      fi

## Build
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build .
  - cmake --build . --target tests
  - ctest .
